require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/importmap'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'config/application.rb'

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/RedundantConstantBase:
  Exclude:
    - 'config/environments/production.rb'
