inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/importmap'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'

Style/FrozenStringLiteralComment:
  Enabled: false